version: '3'
services:
  backend:
    build:
      context: ./backend  # Caminho relativo para a pasta onde o Dockerfile do backend está
      dockerfile: Dockerfile  # (Opcional) nome do Dockerfile, se estiver usando o padrão não precisa
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Link para a pasta do backend
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/pokemon-tcg  # URI de conexão com o MongoDB

  frontend:
    build:
      context: ./frontend  # Caminho relativo para a pasta onde o Dockerfile do frontend está
      dockerfile: Dockerfile  # (Opcional) nome do Dockerfile, se estiver usando o padrão não precisa
    ports:
      - "3001:3000"  # Mapeando a porta do frontend para 3001 na máquina host
    volumes:
      - ./frontend:/app  # Link para a pasta do frontend
      - /app/node_modules
    environment:
      - NODE_ENV=development

  mongo:
    image: mongo:latest  # Usando a imagem oficial do MongoDB
    ports:
      - "27017:27017"  # Mapeando a porta padrão do MongoDB
    volumes:
      - mongo-data:/data/db  # Persistência de dados

volumes:
  mongo-data:  # Volume para persistir os dados do MongoDB
