version: '3'
services:
  backend:
    build:
      context: ./backend  # Caminho relativo para a pasta onde o Dockerfile do backend está
      dockerfile: Dockerfile  # (Opcional) nome do Dockerfile, se estiver usando o padrão não precisa
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app  # Link para a pasta do backend
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend  # Caminho relativo para a pasta onde o Dockerfile do frontend está
      dockerfile: Dockerfile  # (Opcional) nome do Dockerfile, se estiver usando o padrão não precisa
    ports:
      - "3001:3000"  # Mapeando a porta do frontend para 3001 na máquina host
    volumes:
      - ./frontend:/app  # Link para a pasta do frontend
      - /app/node_modules
    environment:
      - NODE_ENV=development
